### ISSUE TITLE
Preparar documento para pedido de patrocínios

### ISSUE THREAD

**Issue by Dayof** [pyladiesdf/DjangoGirls#10]
Documento com pacotes de patrocínio.

**Comment by Dayof** [comment]
@belaeifert ver com @taniaa  e com a Helo para te ajudar com o layout do documento e exemplos de eventos passado, como a Python Brasil.

**Comment by taniaa** [comment]
Minhas indicações públicas:

https://2013.pythonbrasil.org.br/patrocinio/prospectos.html

https://drive.google.com/file/d/0B0fYYHtjOrCAQUIwV0JfWk15ZjQ/view

Também tem uma da @dayof, evento de mulher. Não sei o link.

**Comment by Dayof** [comment]
DOCUMENTO DE PATROCINIO PRONTO! @Heloisecs @belaeifert @Dayof @fabiommendes 

[Plano de Patrocínio - Django Girls 2018.pdf](https://github.com/pyladiesdf/DjangoGirls/files/1913342/Plano.de.Patrocinio.-.Django.Girls.2018.pdf)
