### ISSUE TITLE
Orçar material gráfico das PyLadies DF

### ISSUE THREAD

**Issue by Dayof** [pyladiesdf/DjangoGirls#11]
* [ ] Banner
* [ ] Cartazes

**Comment by naiieandrade** [comment]
-  Nerd Stickers (150)
https://www.nerdstickers.com.br/todos/adesivo-personalizado-corte-especial/
- [x] Fosco emborrachado
- [x] Corte especial
- [x]  5x5 
Sem checagem = 119,55
Com checagem = 144,25

**Comment by belaeifert** [comment]
Gráfica multicor - Núcleo Bandeirante

- Material: ADESIVO VINIL BRILHO;

- Tamanho: 5x5

- Custo: 25 Reais

**Comment by joenio** [comment]
outra opção de orçamento é esse site, alguns amigos relatam de que os adesivos deles são de boa qualidade:

* https://www.stickersdevs.com.br/stickers-personalizados/

**Comment by Dayof** [comment]
@fabiommendes já temos algum orçamento dos banners ?

**Comment by fabiommendes** [comment]
Ainda não  :/

**Comment by belaeifert** [comment]
Banner formato padrão 80x120:  50 reais
Cartazes, tamanho A3:
   - 1,90 cada unidade no papel;
   - 3,15 cada unidade no adesivo.
