### ISSUE TITLE
Orçar camisas

### ISSUE THREAD

**Issue by Dayof** [pyladiesdf/DjangoGirls#12]
Arte : https://store.djangogirls.org/products/fitted-code-like-a-girl-t-shirt
Total : 135

- Participantes
  - Quantidade : 90
  - Cor : Laranja
- Tutoras e Metatutoras
  - Quantidade : 25
  - Cor : Roxo
- Organização
  - Quantidade : 20
  - Cor : Roxo

**Comment by Dayof** [comment]
Orçando com fornecedores de goiânia com ajuda do Elias Junior:

Fornecedores:
- Leo Quique Sports  
  - Contato : +556281314031
- Raoni Rawss 
  - Contato : +556299664574
  - Orçamento : (Elias fechou por R$ 14.5, 100 blusas para o calango)
- Absai Rei 
  - Contato : +556236244160 | +556285111321

**Comment by taniaa** [comment]
Só falta mandar a minha camiseta e fechar a thread <3
