### ISSUE TITLE
Entrar em contato com Zé sobre gráfica

### ISSUE THREAD

**Issue by Dayof** [pyladiesdf/DjangoGirls#18]
Fazer pedido dos seguintes itens:
- 100 cartazes de divulgação  / para colocar no dia do evento (Ver artes ainda)
- 150 Stickers das pyladies

Mais algum item para pedir?

**Comment by Dayof** [comment]
Aguardando arte dos cartazes #14 para pedir a produção dos materiais. @belaeifert vai pegando o contato do zé enquanto isso plz !

**Comment by fabiommendes** [comment]
@joenio você pode ver com o zé se ele consegue uma gráfica que faça nosso material de graça?

**Comment by joenio** [comment]
o Zé me disse que aguardou o contato da Dani Estevam sobre isso mas que ela não entrou em contato com ele, creio que será mais produtivo manter a Dani cuidando disso. Se houver algum problema ou dificuldade de comunicação com o Zé fala comigo que dou um ping nele.
