### ISSUE TITLE
Criar novo site PyLadies usando Pelican

### ISSUE THREAD

**Issue by joenio** [pyladiesdf/DjangoGirls#24]
- [x] Criar conteúdo do site com Pelican usando um fork do https://github.com/pyladies-brazil/br-pyladies-pelican [@joenio @Heloisecs @Dayof ]
- [x] Atualizar as PyLadies DF atuais [@naiieandrade]
- [x] Enviar email para brazil@pyladies.com solicitando a criação do domínio brasilia.pyladies.com [@Dayof]
- [x] Adicionar DNS ```http://df.pyladies.com/``` em vez do atual gerado pelo heroku [@Dayof]

**Comment by naiieandrade** [comment]
- [ ] Enviar email para brazil@pyladies.com solicitando a criação do domínio brasilia.pyladies.com
* Atualizar logo e site usando brasilia.pyladies.com em:
- [ ] https://python.org.br/pyladies/
- [x] http://www.pyladies.com/locations/
- [ ] http://brasil.pyladies.com/locations/
- [x] Criar conteúdo do site com Pelican usando um fork do https://github.com/pyladies-brazil/br-pyladies-pelican [@joenio @Heloisecs @Dayof ]
- [ ] Adicionar domínio brasilia.pyladies.com na wiki do Calango http://calango.club/pyladiesdf
- [x] Remover repositório https://github.com/pyladiesdf/pyladiesbsb.github.io

**Comment by Dayof** [comment]
DONE!

**Comment by naiieandrade** [comment]
:top:
