### ISSUE TITLE
Atualizar novas informações das PyLadies DF

### ISSUE THREAD

**Issue by Dayof** [pyladiesdf/DjangoGirls#25]
- [ ] Atualizar informações sobre PyLadies DF em:
  - [x] https://python.org.br/pyladies/ (https://github.com/pythonbrasil/wiki)
  - [ ] http://www.pyladies.com/locations/ (https://github.com/pyladies/pyladies)
  - [x] http://brasil.pyladies.com/locations/ [@naiieandrade]
- [ ] Adicionar domínio brasilia.pyladies.com na wiki do Calango http://calango.club/pyladiesdf
- [x] Remover repositório https://github.com/pyladiesdf/pyladiesbsb.github.io [@Dayof]

**Comment by naiieandrade** [comment]
@Dayof no python.org já foi atualizado a imagem. Mas como ele (eu acho que é o python.org) puxa do repositório do pyladies brasil, e a imagem ta de tamanho pequeno ficou meio desfocada. Só pra avisar mesmo.
