### ISSUE TITLE
Criar conteúdo no site do DG DF

### ISSUE THREAD

**Issue by Dayof** [pyladiesdf/DjangoGirls#27]
Login no https://djangogirls.org/admin/ para alterar conteúdo no : https://djangogirls.org/brasilia
Quem mais quiser ajudar, perguntar login e senha do admin para @belaeifert e @Dayof.

**Comment by naiieandrade** [comment]
- [x] tá no ar: https://djangogirls.org/brasilia/ :grinning: 
- [ ] Revisar informações @belaeifert
