### ISSUE TITLE
Local e Data

### ISSUE THREAD

**Issue by fabiolamfleury** [pyladiesdf/DjangoGirls#29]
Possivelmente IFB da Ceilândia, a Dani fará reunião com pessoal nessa semana (13/05-17/05) e atualizaremos essa issue

- [x] Verificar datas disponíveis

- [x] Verificar a capacidade do local e qual infraestrutura será fornecida

- [x] Enviar e-mail atualizando o pessoal do Django Girls sobre a mudança de lugar

**Comment by fabiolamfleury** [comment]
Confirmado que vai ser no CDT, estamos com o contato do Bruno para marcar uma reunião conhecer o lugar e os espaços que serão utilizados, bem como a capacidade.

**Comment by fabiolamfleury** [comment]
Não podemos esquecer de enviar o email avisando a mudança de local

**Comment by naiieandrade** [comment]
Att local: Sebraelab 
Data: 17/08

**Comment by lenamiroux** [comment]
Biotic e Sebraelab - 17 de agosto - 8h às 18h
