### ISSUE TITLE
Oficialização do evento

### ISSUE THREAD

**Issue by fabiolamfleury** [pyladiesdf/DjangoGirls#30]
Enviar o pedido de oficialização no site do DG https://djangogirls.org/organize/prerequisites/

**Comment by naiieandrade** [comment]
![image](https://user-images.githubusercontent.com/15681725/58044548-6a094480-7b16-11e9-9a80-053a6352070e.png)

Data: 17/08/2019
Local: UnB (a princípio) 

Ambos podem ser alterados

**Comment by naiieandrade** [comment]
![image](https://user-images.githubusercontent.com/15681725/58764179-763fc980-853a-11e9-989f-b3cef885b32e.png)

:heavy_check_mark:

**Comment by fabiolamfleury** [comment]
@naiieandrade temos que enviar pro pessoal do dg a mudança de lugar, agora que confirmamos que vai ser no CDT.
