### ISSUE TITLE
Organização de orçamento

### ISSUE THREAD

**Issue by fabiolamfleury** [pyladiesdf/DjangoGirls#32]
- [x] Patrocínios - utilizar como modelo o plano de patrocínio do DG passado

- [x] Definir o que será orçado (material gráfico, camisas, alimentação, stickers...)

- [x] Realizar orçamentos (abrir issues separadas se necessário)

**Comment by naiieandrade** [comment]
Patrocinadores do ano passado:
- Espaço 365
- Cotidiano 
- Hepta

**Comment by naiieandrade** [comment]
Levantar gráficas que nos atenderam ano passado, e fazer levantamento de preço assim que tiver definido para quantas meninas serão.
- [x] Crachá
- [x] Sticker
- [x] Cartazes

**Comment by lenamiroux** [comment]
Orçamentos para pré-DG e DG realizados.
