### ISSUE TITLE
Preparatório do Django Girls DF com tutora(e)s selecionados

### ISSUE THREAD

**Issue by fabiolamfleury** [pyladiesdf/DjangoGirls#36]
- [x] Definir data e local do preparatório

**Comment by fabiolamfleury** [comment]
Vai acontecer no lappis, dia 13 de julho! Temos que enviar email e confirmar com as participantes o horário

**Comment by BrunaNayara** [comment]
@fabiolamfleury precisa de mais alguma coisa?
Autorização para abrir o lappis no dia?
Comidinhas (pq é um lugar difícil né)?

**Comment by fabiolamfleury** [comment]
@BrunaNayara seria legal apoio do pessoal do lappis no dia, caso tenha algum problema com a rede ou algo do tipo, acho q é isso que você falou mesmo

**Comment by fabiolamfleury** [comment]
Todas as monitoras até o dia do evento devem:

- [ ] Estar no grupo do telegram

- [ ] Ler as normas de monitoria e notificar sobre a leitura (via e-mail ou no grupo de monitoria) : https://coach.djangogirls.org 

- [ ] Terminar o tutorial do Django Girls e notificar (via e-mail ou no grupo de monitoria) : https://tutorial.djangogirls.org/pt/
