### ISSUE TITLE
Pós DG

### ISSUE THREAD

**Issue by fabiolamfleury** [pyladiesdf/DjangoGirls#38]
- [x] Definir data e local
- [x] Definir atividades que serão realizadas:
1 hora de dinâmica (Dani)
20 minutos de avisos (Nai e Simone)
X minutos de standup (Nai confirma?)
Restante para networking e lanches

Levar:
- [x] Caixa preta
- [x] Copos
- [x] 7 sucos
- [x] 4 refrigerantes

**Comment by fabiolamfleury** [comment]
Será na cotidiano, sugerimos alguma data da semana de 19 a 23 de agosto

**Comment by Aninhaloiola** [comment]
Após reunião com cotidiano o pós DG ficou na data 29 de agosto das 19hrs as 22hrs
