### ISSUE TITLE
Organização da infraestrutura

### ISSUE THREAD

**Issue by fabiolamfleury** [pyladiesdf/DjangoGirls#39]
Checar o que se aplica do que foi levantado nas issues #20, #5 e #4

**Comment by fabiolamfleury** [comment]
Temos que pedir para monitoras levarem extensão e notebooks para serem utilizados por participantes que não tem pc

**Comment by Sleshes** [comment]
eu posso disponibilizar meu notebook e só tenho um filtro de linha curto disponível

**Comment by lenamiroux** [comment]
Elétrica, hidráulica, mobiliário, estacionamento, internet!
### **Lembrar de checar link com internet mesmo que falem que tem internet.**

**Comment by lenamiroux** [comment]
Realizado.
