### ISSUE TITLE
Subir servidor local com Django Girls Tutorial

### ISSUE THREAD

**Issue by Dayof** [pyladiesdf/DjangoGirls#4]
Tutorial : https://tutorial.djangogirls.org/pt/

**Comment by joenio** [comment]
Fiz o setup do GitBook e configurei o tutorial DjangoGirls nele, funcionou redondo, instruções abaixo:

Num `Debian Sid` executar os seguintes passos:

    sudo apt install nodejs npm
    sudo npm install gitbook-cli -g
    git clone https://github.com/DjangoGirls/tutorial.git
    cd tutorial
    gitbook install
    gitbook serve

O tutorial estará disponível em: http://localhost:4000

## Referências

Setup and Installation of GitBook:
* https://github.com/GitbookIO/gitbook/blob/master/docs/setup.md

## Próximos passos

Preparar uma máquina definiva no local no dia do DG Interno (issue #17) e garantir ao menos um roteador wireless pois a rede local e wifi da UnB/Gama cai com frequência.

**Comment by Dayof** [comment]
@joenio tem como subir o material clonado neste repositório porfavor :)?

**Comment by joenio** [comment]
o único material clonado foi esse aqui https://github.com/DjangoGirls/tutorial.git mas n sei se precisamos clonar ele não, ele precisa ser copiado na máquina onde estará disponibilizado o material no dia do evento.

não foi feito nenhuma mudança, o repositório do tutorial será utilizado do jeito que está no "upstream".
