### ISSUE TITLE
Material Gráfico 

### ISSUE THREAD

**Issue by naiieandrade** [pyladiesdf/DjangoGirls#41]
Definir
- [x] Modelos dos stickers
- [x] Banner PyLadies DF
- [x] Cartazes de identificação/informação

**Comment by BrunaNayara** [comment]
@naiieandrade @fabiolamfleury acham que podemos manter a mesmas artes que fizemos pro DG do ano passado?

**Comment by lenamiroux** [comment]
Feito! @simonesymon foi incrível nisso.
