### ISSUE TITLE
Material de divulgação para patrocínio

### ISSUE THREAD

**Issue by naiieandrade** [pyladiesdf/DjangoGirls#42]
- [x] Um template/infográfico com informações sobre o evento DG 2018, PyLadies
- [x] Criar uma apresentação com informações sobre DG 2018, PyLadies para captação de patrocínio

Exemplo: 

![image](https://user-images.githubusercontent.com/15681725/58769283-e9b5fb00-857b-11e9-95d8-29c5c41caa8f.png)

**Comment by heylisten64** [comment]
Bom, nao sou nenhuma designer formada porem eu montei um folderzinho
se não agradar, vou entender ahhah
falta algumas informações q n tinha acesso pois acabei de chegar no projeto @BrunaNayara 
![folder](https://user-images.githubusercontent.com/43069991/58919384-447a5e80-8704-11e9-87e0-5a26996280b9.png)
[folder.pdf](https://github.com/pyladiesdf/DjangoGirls/files/3254789/folder.pdf)

**Comment by fabiolamfleury** [comment]
![image](https://user-images.githubusercontent.com/20935369/59967074-b40d8d80-94fb-11e9-9d03-02819a23873e.png)

Só adicionando a thread a imagem que a @naiieandrade montou com as informações das mídias

**Comment by BrunaNayara** [comment]
@heylisten64 Posso te marcar em outras issues para fazer artes para divulgarmos nas redes sociais?

**Comment by lenamiroux** [comment]
Feito! Imagem publicada.
Atualizar com os dados do evento para patrocínio futuro.
