### ISSUE TITLE
Montar cronograma do evento

### ISSUE THREAD

**Issue by fabiolamfleury** [pyladiesdf/DjangoGirls#43]
- [x] Horários definidos para cada atividade que vai ocorrer

~~A Gabi, que está trabalhando agora na Amazon, gostaria de palestrar no dia.~~ Não vai poder vir

**Comment by fabiolamfleury** [comment]
**Sugestão que tem no site de organização do DG**


The week before the event
Meet your coaches (do a dinner together!). Make sure they're familiar with the Tutorial and Coaches Manual. Get to know everyone and make sure they know each other, too. Exchange ideas and advice.

If you can't do the Installation Party, make sure that coaches contact their group to organize an online party following those instructions

Friday evening - Installation Party!
5pm Meet your attendees and coaches. Give them 30 minutes to get to know each other and talk.

5.30pm Installation starts! Make sure everyone has Python, Pip, Virtualenv and Django installed on their computers. Instructions here!

8pm Invite everyone for a little pre-party to a cafe nearby.

Saturday - big day!
8.30am Doors open, breakfast is served, early registration starts.

9am Welcome everyone, do a short presentation explaining what we're going to do today and what the schedule looks like. Make sure they know they're awesome - the impostor syndrome is strong and you need to break the ice and ensure them they can do it.

9.30am The workshop starts! Teams and coaches should now get to work and follow the tutorial.

12.30pm Time for lunch :) Do a one-hour break. You can also fit some talks by sponsors / invited speakers here. Make sure they're inspiring!

1.30pm Back to the workshop.

6pm Official ending. Again: thank sponsors, coaches and attendees. Make sure they feel awesome. Tell them what they can do next and invite everyone to go for a drink or soda in some place.

6.30pm Wrap-up.

**Comment by naiieandrade** [comment]
08h00 - Recepção e Credenciamento das participantes
09h00 - Abertura do DG e espaço para patrocinadores
10h00 - Workshop - Parte 1
12h00 - Almoço
13h00 - Workshop - Parte 2
16h00 - Coffee Break
17h00 - Fechamento 

@BrunaNayara @fabiolamfleury @simonesymon

**Comment by JuhBass** [comment]
Estava pensando em fazermos uma parceria com o projeto Elas Agitam para termos um entretenimento no fechamento do evento ou nas pausas para almoço/coffee break.

O Elas Agitam é um projeto que ensinou por 3 meses mulheres a serem DJ
