### ISSUE TITLE
Atualizar plano de patrocínio

### ISSUE THREAD

**Issue by BrunaNayara** [pyladiesdf/DjangoGirls#44]
Atualizar plano de patrocínio com os dados dos eventos do ano passado:
- CPBSB
- Pré DG
- Pós DG
- Beer Jobs

https://docs.google.com/document/d/1n8JvJlpPnoQFGkKjQQCYuvMdotEBYlD1pMjgZfDBYP8/edit?usp=sharing

**Comment by fabiolamfleury** [comment]
Atualizei, colocando as seguintes informações:

- Mídias sociais: 
  - Facebook, 639 curtidas, 
  - Twitter, 201 seguidores, 
  - Instagram, 1000 seguidores.
- Informações sobre eventos:
  - Campus Brasília 2018
  - Pré DG 
  - Pós DG
  - Beer Jobs
  - Apoio a Python Cerrado
  - Palestrantes na Campus 2019 de SP
  - Parceria com a Cisco


Coloquei ainda que o número de 'organizadores' da comunidade são 22 (número atual de integrantes do grupo ADM.  Tinha um campo com o número esperado de participantes (que foi usado ano passado) fiquei na dúvida se era pra manter, pq depende do espaço/monitoras, ai marquei um comentário no doc

Outro detalhe, o cronograma das datas de inscrições e etc eu inventei dando uma olhada no do evento do ano passado, talvez não seja dos melhores
