### ISSUE TITLE
Concretização da parceria com a cotidiano para Pré DG

### ISSUE THREAD

**Issue by fabiolamfleury** [pyladiesdf/DjangoGirls#46]
Para concretização do pré dg, precisamos realizar as seguintes atividades:

- [x] Redigir documento para a parceria, dizendo o papel das pyladies (colocar a cotidiano nas mídias, a Lanna vai enviar amanhã os dados) e da cotidiano (prover o espaço para X pessoas, cadeiras ou puffs, projetor, aúdio)

- [x] Criar o sympla do evento e colocar o pessoal da cotidiano como organizador

- [x] Criar o cronograma do evento

- [x] Divulgar nas redes sociais o evento

**Comment by BrunaNayara** [comment]
> Criar o sympla do evento e colocar o pessoal da cotidiano como organizador

Criei a issue #48

**Comment by BrunaNayara** [comment]
> Criar o cronograma do evento

Issue #51

**Comment by BrunaNayara** [comment]
> Divulgar nas redes sociais o evento

Issue #52

**Comment by belaeifert** [comment]
Ainda precisam de ajuda com essa issue?

**Comment by fabiolamfleury** [comment]
Oi @belaeifert enviamos ontem uma primeira versão do documento, o cronograma e a arte pro pessoal da cotidiano, estamos aguardando a resposta deles :)

Seria legal ajuda pra arrumar a parte de mídia do pré dg #52
