### ISSUE TITLE
Atualizar patrocinadores

### ISSUE THREAD

**Issue by fabiolamfleury** [pyladiesdf/DjangoGirls#47]
Adicionar a cotidiano e o cdt no site do django girls

**Comment by BrunaNayara** [comment]
Tem link pro repositório do DG?
Tem arte pra colocar?

**Comment by fabiolamfleury** [comment]
A cotidiano ficou de enviar a arte para a @naiieandrade , de resto quem ver com o pessoal. O site não tem repositório, o pessoal do Django Girls forneceu credenciais para quem enviamos como organizadoras, mas podemos adicionar mais pessoas

**Comment by naiieandrade** [comment]
Recebemos a logo da Cotidiano! :heavy_check_mark:
