### ISSUE TITLE
Criar o Sympla com o evento do pré-DG

### ISSUE THREAD

**Issue by BrunaNayara** [pyladiesdf/DjangoGirls#48]
- [x] Criar o sympla PyLadies DF
- [x] Criar o evento Pré-DG

Detalhes:
Dia:25/07/2019
Hora: 19:00 às 23:00

**Comment by BrunaNayara** [comment]
https://www.sympla.com.br/pre-dg-df__575795

**Comment by fabiolamfleury** [comment]
Precisamos adicionar a cotidiano como organizador do sympla também, mas ainda não enviaram os dados deles

**Comment by BrunaNayara** [comment]
@fabiolamfleury e @naiieandrade quando eles enviarem podem adicionar eles lá, ou me avisar, que eu coloco
