### ISSUE TITLE
Montar o cronograma do Pré-DG

### ISSUE THREAD

**Issue by BrunaNayara** [pyladiesdf/DjangoGirls#51]
Até então, estamos pensando em convidar:
-  professora Gina
- Tânia Fontenele
- @naiieandrade quem era a terceira?

O espaço estará aberto para a organização às 18. 
O evento começa às 19 e termina às 23.

O que tem que ser feito 
- [x] Pensar nas atividades (Painel, roda de conversa, filme, apresentação?)
- [x] Lembrar qual a hora que começa o coffee break
- [x] Definir hora para as atividades e viabilizar

Lembrando que o tema do evento é "Existem outros caminhos" e por isso a escolha de convidadas de backgrounds diferentes.

**Comment by fabiolamfleury** [comment]
Lembrando que tem certa prioridade pois o pessoal da Cotidiano quer o cronograma e a data do evento está próxima :)

**Comment by shayanealcantara** [comment]
Cronograma do ano passado. 
![image](https://user-images.githubusercontent.com/33501171/60837804-841ee500-a19f-11e9-8386-d050a49f1346.png)

Como não fui o do ano passado, peguei ele como inspiração para o desse ano. 
Com as infos que tem aqui na issue, montei esse cronograma:

OBS.: Como soube que ano passado teve pipoca e bebidas, acho que poderia ficar à vontade para as meninas e assim não precisar parar muito tempo para um coffee break.

**19:00**: Filme Estrelas Além do Tempo (2h 5min)
**21:15** Apresentação da professora Gina (40 min)
**21h55** Apresentação da Tania Fontenele (40 min)
**22:35** Informações para o dia do DG (25 min)

Essa é minha sugestão, pensando em outras coisas eu posto aqui :) @BrunaNayara @fabiolamfleury

**Comment by fabiolamfleury** [comment]
Oi Shay, valeu pela contribuição <3 

Então, pensei q trocaríamos o filme esse ano por esse painel de apresentações, da professora Gina, Tania... e depois faríamos a roda de conversa, mas posso estar completamente enganada, vamos ver o que as meninas respondem :) @naiieandrade  @Aninhaloiola

**Comment by fabiolamfleury** [comment]
Enviado em email pro pessoal da cotidiano:

- 19h00-20h30 - Painel de Mulheres: Existem outros caminhos
-  20h45-22h - Roda de Conversa
