### ISSUE TITLE
Seleção de participantes

### ISSUE THREAD

**Issue by fabiolamfleury** [pyladiesdf/DjangoGirls#54]
A seleção será feita dia 18/07. Lembrando que:

- No ano passado, só foi passado pras monitoras as participantes DEPOIS delas terem concluído o tutorial. @naiieandrade @BrunaNayara vamos manter essa lógica?

**Comment by BrunaNayara** [comment]
A divulgação vai ser no dia 18. Mas se puderem fazer antes, não tem problema. 

Acho bom mantermos essa dinâmica.

**Comment by shayanealcantara** [comment]
Quantas vagas teremos para as participantes?

**Comment by naiieandrade** [comment]
- [x] Email enviado às participantes 
- [x] Email perguntando o tamanho da blusa
