### ISSUE TITLE
Pré DG

### ISSUE THREAD

**Issue by naiieandrade** [pyladiesdf/DjangoGirls#55]
- [x]  Organizar Coffee Break (para 50 pessoas) #57 
- [x]  Confirmar participantes do painel @naiieandrade 
- [x]  Divulgar participantes
- [x]  Divulgar artes (quem não for avisar, levar caneca... )

**Comment by naiieandrade** [comment]
Painel de mulheres - "**Existem outros caminhos**"

Dani Estevam
Camilla Siren 
Tânia Fontenele

**Comment by lenamiroux** [comment]
Evento realizado em 25/07 das 19h às 22h na Cotidiano Aceleradora.
