### ISSUE TITLE
Realizar o orçamento das blusas do evento

### ISSUE THREAD

**Issue by fabiolamfleury** [pyladiesdf/DjangoGirls#56]
- [x] Conferir a contagem de blusas

- [x] Fazer o pedido (qual é a data máxima para isso?)

**Comment by fabiolamfleury** [comment]
A parte do orçamento talvez não faça mais sentido mas temos que contar, novamente, a quantidade das blusas, verificar se a organização, participantes e monitoras colocaram o tamanho certo. 

@naiieandrade a camila (siren) passou os tamanhos das dela? tem mais patrocinadores que terão direito?

**Comment by naiieandrade** [comment]
Sim @fabiolamfleury !
Já estamos com a contagem dos patrocinadores, monitoras e faltam 10 participantes! 
:muscle:

**Comment by naiieandrade** [comment]
Sobre a data a @BrunaNayara vai saber

**Comment by lenamiroux** [comment]
Blusas feitas e maravilhosas.
Método de dobra e separação foi muito eficiente.
