### ISSUE TITLE
Divulgação nas mídias do pré DG

### ISSUE THREAD

**Issue by fabiolamfleury** [pyladiesdf/DjangoGirls#58]
- [x] Divulgar painelistas, bio e foto

- [x] Divulgar artes pedindo para avisar quem pegou ingresso e não vai poder 

- [x] Divulgar artes pedindo pra levarem suas canecas/copos

**Comment by belaaiza** [comment]
é só divulgar as artes prontas ou ainda tem que fazer?

**Comment by ghost** [comment]
Tenho a mesma dúvida da IzaCristina
