### ISSUE TITLE
Permissão de uso de imagem/som

### ISSUE THREAD

**Issue by fabiolamfleury** [pyladiesdf/DjangoGirls#59]
Precisamos imprimir esse documento para o dia do evento pedir autorização para as participantes para o uso de imagem e som.

**Comment by naiieandrade** [comment]
Eu já fiz, mas não sei porque só deu 3 por página. Ano passado eram 4. Se alguém quiser dar uma olhada, ta na pasta do DG > Termo. Falta só atualizar as últimas infos para imprimir! @fabiolamfleury

**Comment by fabiolamfleury** [comment]
Formatação arrumada para 4, informações atualizadas pela @naiieandrade e já ta impresso ;)

**Comment by lenamiroux** [comment]
Documentos impressos e assinados.

- [ ] Escanear para arquivo.
