### ISSUE TITLE
Enviar email para possíveis patrocinadores

### ISSUE THREAD

**Issue by fabiolamfleury** [pyladiesdf/DjangoGirls#62]
Temos no e-mail das pyladies um modelo para ser enviado junto com o plano de patrocínio

**Comment by BrunaNayara** [comment]
Exemplo de email


>  Boa tarde, 

> Nós do PyLadies DF estamos organizando o evento Django Girls aqui em Brasília. O objetivo do evento é introduzir mais mulheres à tecnologia dando seus primeiros passos com Python e Django, seguindo o tutorial que foi criado e é melhorado pela comunidade mundial Django Girls. 

> Para organizar o evento aqui em Brasília, contamos com aproximadamente, 15 mulheres na organização trabalhando voluntariamente, além de 40 monitoras que vão ajudar a guiar e instruir as participantes durante o evento seguindo o tutorial. Todo esse trabalho é voluntário e não cobramos ingresso ou taxa de inscrição das participantes. 

> Este ano estamos planejando que o evento aconteça dia 17 de agosto das 09:00 às 18:00 horas. Nós organizamos também um pré e um pós evento para quebrar o gelo, promover discussões, e tirar dúvidas finais. Esses eventos acontecem entre duas e três semanas antes do evento principal (25 de julho  e 27 de agosto). 

> Agora, estamos  em busca de parceiros que possam viabilizar o evento. Como não cobramos taxa de inscrição, os principais gastos que temos são com coffee break, almoço, confecção de camisetas, material de som para o auditório, e material gráfico para caracterização das salas que abrigarão o evento. 

> Os parceiros que patrocinam os eventos também recebem alguns benefícios de acordo com o valor do patrocínio. Em geral, são camisetas, espaço para apresentação na abertura do evento, divulgação nas redes socias, etc.

> Nós acreditamos que a [EMPRESA] possa ter interesse em contribuir com o evento, levar conteúdo para a abertura do evento, além de promoção da empresa. Por isso estamos entrando em contato. 

> Anexei o plano de patrocínio que explica melhor sobre o evento, a comunidade e as cotas de patrocínio. Também está anexado um PDF exemplo para formalizar a parceira entre as partes. 

> A nossa rede social mais ativa é o instagram: https://www.instagram.com/pyladiesdf/ . Caso queiram dar uma olhada em como está indo a organização do evento :)
 

> Obrigada, 
> [SEU NOME]

**Comment by BrunaNayara** [comment]
[Link do plano de patrocínio](https://drive.google.com/file/d/1N03wwCAfZ_Y4JerPZ6OveHUZJxwmasNu/view?usp=sharing)

[Link do modelo de parceria](https://docs.google.com/document/d/1zdCKs551owHDcuHtQG7m-0rO0brFwqSdTGlCgPKchHE/edit?usp=sharing)

**Comment by BrunaNayara** [comment]
[Lista de empresas que já pedimos patrocínio](https://docs.google.com/spreadsheets/d/1o1maEduxT9vOpYaNoFokKiPCm5TS8ENLoRROBdjvEaI/edit?usp=sharing)
