### ISSUE TITLE
Emissão de certificados para participantes e monitoras

### ISSUE THREAD

**Issue by fabiolamfleury** [pyladiesdf/DjangoGirls#65]

**Comment by lenamiroux** [comment]
Certificados na pasta do Drive:
Participantes - https://drive.google.com/drive/folders/1d_DRVWsiC9LjCIs_o3xEKeZdFcfjkicB
Monitoras - https://drive.google.com/drive/folders/1kRJ9vAZSuwG8CLvPUHkBJFV6s_8De7kJ
Organização - https://drive.google.com/drive/folders/1tJfxaGYrB_b6s_W9lFRE3nteY1dIzFpo

- [x] Enviar certificados para Participantes
- [x] Enviar certificados para Monitoras (temos email delas na planilha?)
- [ ] Enviar certificados para Organização

**Comment by shayanealcantara** [comment]
@lenamiroux O link de participantes está duplicado na descrição, pode atualizar?

**Comment by fabiolamfleury** [comment]
@lenamiroux temos os emails delas na planilha, enviamos a pasta com todos os certificados por e-mail para elas procurarem?

**Comment by lenamiroux** [comment]
Estou tentando criar um script de GoogleScript pra ver se conseguimos enviar. Me dei o prazo de hoje. Se não rolar enviamos o link.

**Comment by lenamiroux** [comment]
@shayanealcantara modifiquei os links mas também desliguei o compartilhamento por link pq esses comentários são públicos.

**Comment by lenamiroux** [comment]
Certificados para participantes enviados com Script.
Planilha de monitoras precisa dos dados de e-mail.
Organização deve pegar arquivos na pasta.

**Comment by fabiolamfleury** [comment]
Planilha das monitoras atualizada ;)

**Comment by BrunaNayara** [comment]
Esse link tá desatualizado :(

**Comment by BrunaNayara** [comment]
Os links para as pastas com os certificados estão atualizados no comentário da @lenamiroux. Certificados prontinhos. Obrigada a todas!
