### ISSUE TITLE
Preparar After DG !

### ISSUE THREAD

**Issue by Dayof** [pyladiesdf/DjangoGirls#8]
Ver local (reserva) e espaço suficiente para o after ! :D

**Comment by naiieandrade** [comment]
O que seria exatamente o after?

**Comment by Dayof** [comment]
Encontro social/momento de descontração pós DG ! A ladytron quer cuidar disso também/conhece lugares legais pelo da unb/gama, mas se tiver recomendações também vai ser legal!

**Comment by naiieandrade** [comment]
ah sim, eu moro no gama. Tem algumas opções de bares e lanchonetes, dependendo do que queriam.
Tem o barbosinha que tem espetinho, petiscos e bebidas, mas é sempre cheio e meio alto lá o barulho (não sei explicar, rs, mas é em conta)
Tem pizzaria, Tio Sam, Max Burguer
Tem hamburgueria, nerds burguer, bulls(mas acho muito caro)
De bar, tem o armazém 21, o sarará 
De bar barato, tem o JC que é bem conhecido, mas geralmente o pessoal que gosta de ir la é mais para beber, mas tem pastel e outras opções tb
Enfim, ta ai algumas opções, ladytron

**Comment by joenio** [comment]
tantas opções, isso é bom! eu só conheço o barbosinha, tinha pensado em ser lá, mas talvez essa questão de ser cheio d+ atrapalhe, de lá gosto do preço e da comida, creio que a cerveja tb tem um preço justo.

@naiieandrade o que você sugere?
