### ISSUE TITLE
Coffee Break

### ISSUE THREAD

**Issue by Dayof** [pyladiesdf/DjangoGirls#9]
Orçar coffee break para 140 pessoas, para o período da manhã e da tarde para o dia 11 de Agosto.

**Comment by carolinaferreira** [comment]
COFFEE BREAK PARA 140 PESSOAS

CARDÁPIO

- bolo de milho cremoso
- bolo de laranja
- pão de queijo
- mini-sanduíche (brioche)
- quiche de alho poró
- pão pizza
- esfirra de carne
- empada de frango
- croissant romeu e julieta
- salada de frutas
- mini-sonhos
- mini-broas temperadas

BEBIDAS 

- água
- café
- leite
- chás (erva doce e mate)
- suco (abacaxi com hortelã e maracujá)
- refrigerante (coca-cola, coca-zero e guaraná antarctica)

MATERIAL DE USO 

- boleiras
- colheres
- taças 
- cumbucas
- compoteiras
- bandeijas 
- suqueiras
- guardanapos 
- toalha p mesa de buffet 
- arranjo p mesa de buffet 

PESSOAL DE SERVIÇO 

- 01 chefe de cozinha 
- 01 auxiliar de cozinha
- 02 garçons

VALOR TOTAL: R$ 30,00/pessoa.

Qualquer dúvida, estou a disposição! 

Atenciosamente,

Tatiani Peixoto 
CANDANGO'S BUFFET

**VALOR FINAL: R$ 4.200,00**

**Comment by carolinaferreira** [comment]
**VALOR COM CARDÁPIO REDUZIDO** se preciso, podemos reduzir mais

COFFEE BREAK PARA 140 PESSOAS

CARDÁPIO

- bolo de milho cremoso
- bolo de laranja
- pão de queijo
- pão pizza
- esfirra de carne
- empada de frango
- croissant romeu e julieta
- salada de frutas

BEBIDAS 

- água
- café
- chás (erva doce e mate)
- suco (abacaxi com hortelã e maracujá)
- refrigerante (coca-cola, coca-zero e guaraná antarctica)

MATERIAL DE USO 

- boleiras
- colheres
- taças 
- cumbucas
- compoteiras
- bandeijas 
- suqueiras
- guardanapos 
- toalha p mesa de buffet 
- arranjo p mesa de buffet 

PESSOAL DE SERVIÇO 

- 01 chefe de cozinha 
- 01 auxiliar de cozinha
- 02 garçons

VALOR TOTAL: R$ 23,00/pessoa.

Qualquer dúvida, estou a disposição! 

Atenciosamente,

Tatiani Peixoto 
CANDANGO'S BUFFET

**VALOR FINAL: R$ 3.220,00**

**Comment by carolinaferreira** [comment]
CARDÁPIO

- Bolo;
- Salgados,
- Patês;
- Pães;
- Queijo;
- Presunto;
- Manteiga;
- Frutas laminadas.

BEBIDAS
- Suco (2 sabores);
- Chá;
- Café;
- Leite;
- Achocolatado;
- Refrigerantes.

Possui uma equipe completa para repor os alimentos e servir as bebidas.

VALOR TOTAL: R$ 15,00/pessoa.
Janete

**VALOR FINAL: R$ 2.100,00**
